apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend-service
  namespace: capstone-frontend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: capstone-frontend-app
  type: LoadBalancer
